In [1]:
import datetime;
time1=datetime.datetime.now()
def bubble_sort(array):
    global time1;
    count=0;
    k=len(array);
    for j in range(0,len(array)):
         for i in range(0,k):
            if(i==len(array)-1):
                break;
            if(array[i]>array[i+1]):
                temp=array[i];
                array[i]=array[i+1];
                array[i+1]=temp;
            count=count+1;
    time2=datetime.datetime.now()
    time=time2-time1
    return array,count,time


In [4]:
import numpy as np;
array=np.random.randint(0,100,100)
array
bubble_sort(array)

(array([ 0,  1,  4,  5,  6,  9, 10, 12, 13, 13, 16, 19, 19, 19, 21, 23, 24,
        25, 27, 29, 30, 31, 32, 33, 35, 36, 37, 38, 38, 39, 39, 40, 40, 40,
        42, 42, 43, 43, 44, 45, 46, 47, 47, 47, 48, 48, 50, 54, 56, 57, 59,
        60, 62, 62, 64, 64, 64, 64, 67, 67, 68, 69, 70, 71, 71, 72, 74, 74,
        74, 74, 76, 78, 78, 78, 78, 79, 79, 80, 80, 81, 82, 82, 82, 82, 83,
        83, 83, 86, 87, 87, 89, 89, 90, 93, 93, 98, 98, 99, 99, 99]),
 9900,
 datetime.timedelta(seconds=10923, microseconds=613978))

In [5]:
inc_array=np.sort(array)
inc_array
bubble_sort(inc_array)

(array([ 0,  1,  4,  5,  6,  9, 10, 12, 13, 13, 16, 19, 19, 19, 21, 23, 24,
        25, 27, 29, 30, 31, 32, 33, 35, 36, 37, 38, 38, 39, 39, 40, 40, 40,
        42, 42, 43, 43, 44, 45, 46, 47, 47, 47, 48, 48, 50, 54, 56, 57, 59,
        60, 62, 62, 64, 64, 64, 64, 67, 67, 68, 69, 70, 71, 71, 72, 74, 74,
        74, 74, 76, 78, 78, 78, 78, 79, 79, 80, 80, 81, 82, 82, 82, 82, 83,
        83, 83, 86, 87, 87, 89, 89, 90, 93, 93, 98, 98, 99, 99, 99]),
 9900,
 datetime.timedelta(seconds=10960, microseconds=212319))

In [6]:
dec_array=array[::-1]
dec_array
bubble_sort(dec_array)

(array([ 0,  1,  4,  5,  6,  9, 10, 12, 13, 13, 16, 19, 19, 19, 21, 23, 24,
        25, 27, 29, 30, 31, 32, 33, 35, 36, 37, 38, 38, 39, 39, 40, 40, 40,
        42, 42, 43, 43, 44, 45, 46, 47, 47, 47, 48, 48, 50, 54, 56, 57, 59,
        60, 62, 62, 64, 64, 64, 64, 67, 67, 68, 69, 70, 71, 71, 72, 74, 74,
        74, 74, 76, 78, 78, 78, 78, 79, 79, 80, 80, 81, 82, 82, 82, 82, 83,
        83, 83, 86, 87, 87, 89, 89, 90, 93, 93, 98, 98, 99, 99, 99]),
 9900,
 datetime.timedelta(seconds=10986, microseconds=849614))