In [1]:
import datetime;

def insertion_sort(array):
    a=datetime.datetime.now();
    count=0
    for i in range(1,len(array)):
        for j in range(0,i+1):
            count=count+1
            if(array[j]>array[i]) :
                u=array[i]
                for y in range(i,j,-1) :
                    array[y]=array[y-1]
                array[j]=u
    b=datetime.datetime.now()
    return array,count,b-a

In [7]:
import numpy as np;
array=np.random.randint(0,100,100)
insertion_sort(array)

(array([ 0,  1,  1,  4,  5,  5,  5,  5,  8, 10, 11, 11, 12, 13, 13, 17, 17,
        19, 19, 20, 20, 21, 22, 27, 28, 33, 33, 34, 34, 36, 39, 42, 43, 43,
        44, 44, 45, 45, 45, 46, 47, 47, 49, 50, 51, 51, 53, 53, 54, 55, 58,
        58, 59, 59, 62, 62, 65, 65, 66, 67, 67, 68, 68, 71, 71, 71, 73, 74,
        75, 76, 77, 78, 79, 79, 82, 82, 83, 83, 83, 84, 86, 86, 87, 88, 89,
        89, 90, 91, 91, 91, 92, 92, 93, 93, 94, 95, 97, 98, 98, 98]),
 5049,
 datetime.timedelta(microseconds=7263))

In [6]:
inc_array=np.sort(array)
inc_array
insertion_sort(inc_array)

(array([ 0,  1,  3,  3,  4,  6,  6,  6,  7,  7,  7,  7,  8,  8,  8, 11, 11,
        12, 13, 14, 14, 15, 16, 16, 17, 17, 18, 19, 19, 21, 23, 24, 26, 27,
        27, 27, 28, 29, 29, 30, 32, 33, 35, 35, 38, 38, 44, 45, 46, 46, 47,
        50, 51, 51, 52, 53, 53, 54, 57, 57, 57, 60, 61, 61, 62, 65, 67, 67,
        71, 73, 73, 73, 73, 73, 75, 75, 75, 76, 76, 79, 79, 80, 81, 85, 86,
        87, 88, 88, 88, 89, 89, 90, 92, 92, 93, 95, 95, 97, 97, 99]),
 5049,
 datetime.timedelta(microseconds=5575))

In [8]:
dec_array=array[::-1]
dec_array
insertion_sort(dec_array)

(array([ 0,  1,  1,  4,  5,  5,  5,  5,  8, 10, 11, 11, 12, 13, 13, 17, 17,
        19, 19, 20, 20, 21, 22, 27, 28, 33, 33, 34, 34, 36, 39, 42, 43, 43,
        44, 44, 45, 45, 45, 46, 47, 47, 49, 50, 51, 51, 53, 53, 54, 55, 58,
        58, 59, 59, 62, 62, 65, 65, 66, 67, 67, 68, 68, 71, 71, 71, 73, 74,
        75, 76, 77, 78, 79, 79, 82, 82, 83, 83, 83, 84, 86, 86, 87, 88, 89,
        89, 90, 91, 91, 91, 92, 92, 93, 93, 94, 95, 97, 98, 98, 98]),
 5049,
 datetime.timedelta(microseconds=6994))