In [14]:
import datetime;

def find_leastvalue(i,j,array):
    location=i;
    if(i<=j):
        for item in range(i+1,j):
            if(array[item]<array[location]):
                location=item;
    return location
time1=datetime.datetime.now()
def selection_sort(array):
    global time1;
    count=0;
    k=0;
    for i in range(0,len(array)):
        if(i==len(array)-1):
            break;
        k=find_leastvalue(i+1,len(array),array);
        count=count+1;
        if(array[i]>array[k]):
            temp=array[i];
            array[i]=array[k];
            array[k]=temp;
    time2=datetime.datetime.now()
    time=time2-time1
    return array,count,time


In [16]:
import numpy as np;
array=np.random.randint(0,100,100)
array
selection_sort(array)

(array([ 0,  1,  1,  3,  5,  6,  7,  7,  8,  9, 11, 12, 12, 13, 17, 19, 21,
        21, 23, 25, 25, 26, 28, 28, 29, 31, 32, 35, 36, 38, 38, 40, 40, 41,
        42, 43, 43, 47, 47, 47, 48, 49, 49, 49, 51, 52, 55, 56, 56, 57, 58,
        58, 58, 59, 59, 60, 61, 63, 64, 65, 65, 65, 65, 66, 67, 70, 70, 71,
        71, 71, 72, 72, 73, 78, 79, 79, 79, 79, 80, 80, 80, 81, 81, 81, 82,
        84, 86, 87, 90, 90, 95, 95, 95, 95, 96, 96, 96, 97, 98, 99]),
 99,
 datetime.timedelta(seconds=38, microseconds=817152))

In [17]:
inc_array=np.sort(array)
inc_array
selection_sort(inc_array)

(array([ 0,  1,  1,  3,  5,  6,  7,  7,  8,  9, 11, 12, 12, 13, 17, 19, 21,
        21, 23, 25, 25, 26, 28, 28, 29, 31, 32, 35, 36, 38, 38, 40, 40, 41,
        42, 43, 43, 47, 47, 47, 48, 49, 49, 49, 51, 52, 55, 56, 56, 57, 58,
        58, 58, 59, 59, 60, 61, 63, 64, 65, 65, 65, 65, 66, 67, 70, 70, 71,
        71, 71, 72, 72, 73, 78, 79, 79, 79, 79, 80, 80, 80, 81, 81, 81, 82,
        84, 86, 87, 90, 90, 95, 95, 95, 95, 96, 96, 96, 97, 98, 99]),
 99,
 datetime.timedelta(seconds=82, microseconds=467680))

In [18]:
dec_array=array[::-1]
dec_array
selection_sort(dec_array)

(array([ 0,  1,  1,  3,  5,  6,  7,  7,  8,  9, 11, 12, 12, 13, 17, 19, 21,
        21, 23, 25, 25, 26, 28, 28, 29, 31, 32, 35, 36, 38, 38, 40, 40, 41,
        42, 43, 43, 47, 47, 47, 48, 49, 49, 49, 51, 52, 55, 56, 56, 57, 58,
        58, 58, 59, 59, 60, 61, 63, 64, 65, 65, 65, 65, 66, 67, 70, 70, 71,
        71, 71, 72, 72, 73, 78, 79, 79, 79, 79, 80, 80, 80, 81, 81, 81, 82,
        84, 86, 87, 90, 90, 95, 95, 95, 95, 96, 96, 96, 97, 98, 99]),
 99,
 datetime.timedelta(seconds=123, microseconds=375892))

In [12]:
selection_sort(array)

(array([ 1,  1,  2,  2,  3,  5,  5,  6,  9, 10, 10, 11, 12, 12, 14, 14, 15,
        16, 17, 17, 18, 18, 19, 20, 23, 24, 24, 26, 27, 27, 28, 28, 29, 30,
        34, 35, 37, 37, 38, 40, 40, 42, 43, 44, 44, 47, 48, 49, 49, 52, 53,
        53, 54, 54, 54, 56, 57, 57, 58, 58, 60, 61, 62, 63, 64, 65, 65, 66,
        66, 67, 68, 68, 69, 69, 72, 75, 76, 77, 79, 80, 80, 81, 81, 82, 82,
        83, 84, 85, 87, 89, 89, 91, 91, 91, 92, 93, 94, 96, 97, 97]),
 99,
 datetime.timedelta(seconds=3, microseconds=643961))